### ISSUE TITLE
Storing the current teaser in the language file is nonsense

### ISSUE THREAD

**Issue by Hartmut63** [cmsimple-xh/teaser#2]
Beim Aufruf des Plugins Teaser 1.2.1 im Adminmenü werden im Debugmodus folgende Fehlermeldungen angezeigt:
NOTICE: Undefined index: legal
/xx..xx/cms-drkbu-XH17x/plugins/teaser/admin.php:402
NOTICE: Undefined index: legal
/xx..xx/cms-drkbu-XH17x/plugins/teaser/admin.php:403

Beim Aufruf einer *.txt Teaser Datei (zur Bearbeitung) werden im Debug-Modus folgenden Meldungen angezeigt:
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:3
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:4
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:5
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:6
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:7
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:8
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:9
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:10
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:11
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:12
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:13
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:14
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:15
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:16
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:17
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:18
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:19
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:20
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:21
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:22
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:23
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:24
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:25
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:26
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:27
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:28
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:29
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:30
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:31
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:32
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:33
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:34
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:35
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:36
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:37
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:38
NOTICE: Indirect modification of overloaded element of XH\PluginConfig has no effect
/xx..xx/cms-drkbu-XH17x/plugins/teaser/languages/de.php:39
NOTICE: Undefined index: legal
/xx..xx/cms-drkbu-XH17x/plugins/teaser/admin.php:402
NOTICE: Undefined index: legal
/xx..xx/cms-drkbu-XH17x/plugins/teaser/admin.php:403

Arbeitsumgebung des Plugins:
CMSimple_XH 1.7.2, PHP 5.6.33, Apache/2.4.29 (Unix)

**Comment by cmb69** [comment]
Danke für den Bugreport!

Das erste Problem ("Undefined index: legal") habe ich [behoben](https://github.com/cmsimple-xh/teaser/commit/a4e371ef48f0e4a8cb812a8fb7c8da0d5d4102fc).

Das zweite Problem ("Indirect modification of overloaded element of XH\PluginConfig has no effect") ist hier kniffliger. Der [Code](https://github.com/cmsimple-xh/teaser/blob/1.2.1/admin.php#L496-L504) der diese Meldungen verursacht, müsste wohl komplett erfernt, und der Grund, warum die Sprachdatei überhaupt geändert wird, beseitigt werden. Andernfalls besteht laut Code-Kommentar wohl dieses Problem: "higher value than available teasers can lead to unwanted multiplication of teasers".

PS: das Problem scheint noch weitreichender. Das Plugin scheint die zuletzt bearbeitete Teaserdatei in der Sprachdatei zu speichern. Das könnte in die Session (oder ein Cookie) verlegt werden.
